// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tennis.Application.Data;

#nullable disable

namespace Tennis.Application.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260918163329_AddLadders")]
    partial class AddLadders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tennis.Domain.Entities.Ladder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LaunchedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("ladders", null, t =>
                        {
                            t.HasCheckConstraint("CK_ladders_status", "\"Status\" IN ('Draft', 'Active')");
                        });
                });

            modelBuilder.Entity("Tennis.Domain.Entities.LadderMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("LadderId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Position")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("LadderId", "Position")
                        .IsUnique()
                        .HasFilter("\"Position\" IS NOT NULL");

                    b.HasIndex("LadderId", "UserId", "Role")
                        .IsUnique();

                    b.ToTable("ladder_memberships", null, t =>
                        {
                            t.HasCheckConstraint("CK_ladder_memberships_position", "(\"Role\" = 'Organizer' AND \"Position\" IS NULL) OR (\"Role\" = 'Player' AND \"Position\" > 0)");

                            t.HasCheckConstraint("CK_ladder_memberships_role", "\"Role\" IN ('Organizer', 'Player')");
                        });
                });

            modelBuilder.Entity("Tennis.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTimeOffset>("LastSeenUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Tennis.Domain.Entities.UserAuthIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("LinkedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Subject")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("user_auth_identities", (string)null);
                });

            modelBuilder.Entity("Tennis.Domain.Entities.Ladder", b =>
                {
                    b.HasOne("Tennis.Domain.Entities.User", "CreatedByUser")
                        .WithMany("CreatedLadders")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("Tennis.Domain.Entities.LadderMembership", b =>
                {
                    b.HasOne("Tennis.Domain.Entities.Ladder", "Ladder")
                        .WithMany("Memberships")
                        .HasForeignKey("LadderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tennis.Domain.Entities.User", "User")
                        .WithMany("LadderMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ladder");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tennis.Domain.Entities.UserAuthIdentity", b =>
                {
                    b.HasOne("Tennis.Domain.Entities.User", "User")
                        .WithMany("AuthIdentities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tennis.Domain.Entities.Ladder", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("Tennis.Domain.Entities.User", b =>
                {
                    b.Navigation("AuthIdentities");

                    b.Navigation("CreatedLadders");

                    b.Navigation("LadderMemberships");
                });
#pragma warning restore 612, 618
        }
    }
}
